ELEARN_BACKEND/ELEARN_BACKEND/urls.py
from django.contrib import admin
from django.urls import path, include  
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path('admin/', admin.site.urls),
   
    path('student/',include('STUDENT.urls')),
    path('instructor/',include('INSTRUCTOR.urls')),
    path('',include('HOME_AREA.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path("__reload__/", include("django_browser_reload.urls")), # for refresh tailwind 
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ELEARN_BACKEND/HOME_AREA/urls.py
from django.urls import path 
from . import views, forms, REGLOG, APIs
app_name ='HOME_AREA'
urlpatterns = [
   #registeration, log in functionalities
    path('INSTRUCTOR_REG',REGLOG.instructor_reg_form, name="instructor_reg_form"),
    path('INSTRUCTOR_LOG',REGLOG.instructor_login , name ="instructor_login"),
    path('STUDENT_REG', REGLOG.student_reg_form, name="student_reg_form"),
    path('STUDENT_LOG',REGLOG.student_login, name ="student_login"),
    path("VERIFICATION/<str:user_type>",REGLOG.Verify , name="Verify" ),
    path("forget/<str:user_type>",REGLOG.Forget , name="Forget" ),
    path("logout",REGLOG.Logout, name='Logout'),
    path("editpass/<str:user_type>",REGLOG.EditPass, name='EditPass'),
    path('AccessChatRoom/<str:courseName>/<str:userCat>', views.AccessChatRoom , name = 'AccessChatRoom'),
    path('SaveChats/', views.SaveTOchat, name = 'SaveTOchat'),
    #api views
    path('courses/', APIs.CourseListView.as_view(), name='course-list'),
    path('courses/<str:courseName>/', APIs.CourseDetailsFullView.as_view(), name='course-details-full'),
    path('courses/general/<str:courseName>/', APIs.CourseDetailsGeneralView.as_view(), name='course-details-general'),



    #courses functionalities
    path("Course_Details/<str:courseName>",views.Course_Details, name= 'Course_Details'),
    path('',views.index , name ="index"),



]

ELEARN_BACKEND/STUDENT/urls.py
from django.urls import path
from . import views , APIs
# declaring namespace so i can use these views from anywhere 
app_name = 'STUDENTS'
urlpatterns = [
    #dashboard area
    path('Dashboard/<str:studentName>', views.Dashboard, name = 'DashboardWithUserName'),
    path('Dashboard', views.Dashboard, name = 'Dashboard'),

    path('DropCourse/<str:courseName>', views.DropCourse, name = 'DropCourse'),
    path('EditProfileLink',views.EditProfileLink , name = 'EditProfileLink'),
    path('EditProfile',views.EditProfile, name = 'EditProfile'),
    path('update-status/', views.update_status, name='update_status'),
    path('AddReview/<str:courseName>', views.AddReview, name = 'AddReview'),
    path('RemoveBlockRequest/<str:courseName>',views.RemoveBlockRequest, name = 'RemoveBlockRequest'),
    path('AddRating/<str:courseName>', views.AddRating, name = 'AddRating'),

    path('enrol/<str:courseName>/', views.Enroll, name='Enroll'),  # Make sure there is a trailing slash

    #student APIs area################
    path('APIs/Forms/ForgetPassStudentAPI',APIs.ForgetPassStudentAPI.as_view(), name = 'ForgetPassStudentAPI'),
    path('APIs/Forms/VerifyStudentAPI',APIs.VerifyStudentAPI.as_view(), name = 'VerifyStudentAPI'),
    path('APIs/Forms/StudentLogAPI',APIs.StudentLogAPI.as_view(), name = 'StudentLogAPI'),
    path('APIs/Forms/StudentReg',APIs.StudentReg.as_view()),
    path('APIs/<str:course__COURSE_NAME>',APIs.COURSE_student_APIs.as_view()),
    # to avoid collision with the above url
    path('API/<str:USER_NAME>', APIs.StudentApi.as_view()),
   


]

ELEARN_BACKEND/theme/templates/base.html
{% load static tailwind_tags %}
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} Home page {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% tailwind_css %}

    {% block css %}
    <link rel="stylesheet" href="{% static 'css/dist/home.css' %}" />
    {% endblock %}
</head>
<body class="bg-gray-50 font-serif leading-relaxed text-gray-800">

<header class="bg-white shadow-md py-4">
    <div class="container mx-auto flex justify-between items-center">
        <div class="title-area">
            <h1 class="text-3xl font-bold text-gray-900">Welcome to FreeCoursera</h1>
            <p class="text-lg text-gray-600">It is free and always will be free</p>
        </div>
        <nav class="flex space-x-8">
            <a href="{% url 'HOME_AREA:index' %}" class="text-blue-600 hover:text-blue-800">HomePage</a>
            {% if user.user_cat and user.Isactive%}
           
            <p class="text-gray-700">Welcome, {{ user }}</p>
            <a href="{% url 'HOME_AREA:Logout' %}" class="text-blue-600 hover:text-blue-800">Log out</a>
            {% with user.user_cat|get_dashboard_url as dash_url %}
            
            <a href="{% url dash_url %}" class="text-blue-600 hover:text-blue-800">Dashboard</a>
            {% endwith %}
            {% else %}
            <div class="flex space-x-6">
                <div class="student-area">
                    <a href="{% url 'HOME_AREA:student_reg_form' %}" class="text-blue-600 hover:text-blue-800">Learner Registration</a>
                    <a href="{% url 'HOME_AREA:student_login' %}" class="text-blue-600 hover:text-blue-800">Learner Log in</a>
                </div>
                <div class="instructor-area">
                    <a href="{% url 'HOME_AREA:instructor_reg_form' %}" class="text-blue-600 hover:text-blue-800">Instructor Registration</a>
                    <a href="{% url 'HOME_AREA:instructor_login' %}" class="text-blue-600 hover:text-blue-800">Instructor Log in</a>
                </div>
            </div>
            {% endif %}
            <a href="{%url 'swagger-ui'%}" class="text-blue-400 hover:text-blue-400">Developer? click here for APIs</a>
        </nav>
    </div>
</header>

<div class="container mx-auto py-8">
    {% block main %}{% endblock %}
</div>

</body>
</html>