ELEARN_BACKEND/ELEARN_BACKEND/urls.py
from django.contrib import admin
from django.urls import path, include  
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path('admin/', admin.site.urls),
   
    path('student/',include('STUDENT.urls')),
    path('instructor/',include('INSTRUCTOR.urls')),
    path('',include('HOME_AREA.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path("__reload__/", include("django_browser_reload.urls")), # for refresh tailwind 
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ELEARN_BACKEND/HOME_AREA/urls.py
from django.urls import path 
from . import views, forms, REGLOG, APIs
app_name ='HOME_AREA'
urlpatterns = [
   #registeration, log in functionalities
    path('INSTRUCTOR_REG',REGLOG.instructor_reg_form, name="instructor_reg_form"),
    path('INSTRUCTOR_LOG',REGLOG.instructor_login , name ="instructor_login"),
    path('STUDENT_REG', REGLOG.student_reg_form, name="student_reg_form"),
    path('STUDENT_LOG',REGLOG.student_login, name ="student_login"),
    path("VERIFICATION/<str:user_type>",REGLOG.Verify , name="Verify" ),
    path("forget/<str:user_type>",REGLOG.Forget , name="Forget" ),
    path("logout",REGLOG.Logout, name='Logout'),
    path("editpass/<str:user_type>",REGLOG.EditPass, name='EditPass'),
    path('AccessChatRoom/<str:courseName>/<str:userCat>', views.AccessChatRoom , name = 'AccessChatRoom'),
    path('SaveChats/', views.SaveTOchat, name = 'SaveTOchat'),
    #api views
    path('courses/', APIs.CourseListView.as_view(), name='course-list'),
    path('courses/<str:courseName>/', APIs.CourseDetailsFullView.as_view(), name='course-details-full'),
    path('courses/general/<str:courseName>/', APIs.CourseDetailsGeneralView.as_view(), name='course-details-general'),



    #courses functionalities
    path("Course_Details/<str:courseName>",views.Course_Details, name= 'Course_Details'),
    path('',views.index , name ="index"),



]

ELEARN_BACKEND/STUDENT/urls.py
from django.urls import path
from . import views , APIs
# declaring namespace so i can use these views from anywhere 
app_name = 'STUDENTS'
urlpatterns = [
    #dashboard area
    path('Dashboard/<str:studentName>', views.Dashboard, name = 'DashboardWithUserName'),
    path('Dashboard', views.Dashboard, name = 'Dashboard'),

    path('DropCourse/<str:courseName>', views.DropCourse, name = 'DropCourse'),
    path('EditProfileLink',views.EditProfileLink , name = 'EditProfileLink'),
    path('EditProfile',views.EditProfile, name = 'EditProfile'),
    path('update-status/', views.update_status, name='update_status'),
    path('AddReview/<str:courseName>', views.AddReview, name = 'AddReview'),
    path('RemoveBlockRequest/<str:courseName>',views.RemoveBlockRequest, name = 'RemoveBlockRequest'),
    path('AddRating/<str:courseName>', views.AddRating, name = 'AddRating'),

    path('enrol/<str:courseName>/', views.Enroll, name='Enroll'),  # Make sure there is a trailing slash

    #student APIs area################
    path('APIs/Forms/ForgetPassStudentAPI',APIs.ForgetPassStudentAPI.as_view(), name = 'ForgetPassStudentAPI'),
    path('APIs/Forms/VerifyStudentAPI',APIs.VerifyStudentAPI.as_view(), name = 'VerifyStudentAPI'),
    path('APIs/Forms/StudentLogAPI',APIs.StudentLogAPI.as_view(), name = 'StudentLogAPI'),
    path('APIs/Forms/StudentReg',APIs.StudentReg.as_view()),
    path('APIs/<str:course__COURSE_NAME>',APIs.COURSE_student_APIs.as_view()),
    # to avoid collision with the above url
    path('API/<str:USER_NAME>', APIs.StudentApi.as_view()),
   


]

ELEARN_BACKEND/STUDENT/models.py
from django.db import models
from django.core.validators import MinLengthValidator, RegexValidator
# instead of importing i used lazy loading by using appname.model string
# Create your models here.
class STUDENT(models.Model):
    FIRST_NAME = models.CharField(max_length=50 , null=False , blank=False)
    LAST_NAME = models.CharField(max_length=50 , null=False , blank=False)
    USER_NAME = models.CharField(max_length=50 , null=False , blank=False, unique=True)
    EMAIL = models.EmailField(null=False , blank=False, unique=True)
    PHONE = models.CharField(max_length=15 , null=False, blank=False, unique=True)
    last_login = models.DateTimeField(null=True, blank=True)  # Add last_login field

    PICTURE = models.ImageField(upload_to='images/', blank=True, null= True)
    PASSWORD = models.CharField(null=False, blank=False, max_length=12,
     validators=[
            MinLengthValidator(8),  # Minimum length of 8 characters
            RegexValidator(
                regex=r'^(?=.*[a-z])(?=.*\d)[a-zA-Z\d]{8,}$',
                message="Password must contain at least one lowercase letter and one digit.",
            ),
        ]
    )
    Isactive = models.BooleanField(default = False)
    #useless just to overcome basebackend class and apis requirements
    is_active = models.BooleanField(default = True)

    #all courses that student registered for 
    courseList = models.ManyToManyField('HOME_AREA.COURSES', through='COURSE_LIST')

    def __str__(self) :
        return self.USER_NAME
    
    @property
    def user_cat(self):
        return "student"


    class Meta:
         verbose_name_plural = "Students"
         permissions=[
            ("ENROLL","LEAVE_REVIEW")
         ]

class COURSE_LIST(models.Model):
    student = models.ForeignKey('STUDENT', on_delete=models.DO_NOTHING)
    course = models.ForeignKey('HOME_AREA.COURSES',  on_delete=models.DO_NOTHING)
# verifier user (register, edit password, delete account, ..etc)
class CODE_GENERATOR(models.Model):
    USER_VERIFIER = models.ForeignKey('STUDENT', on_delete=models.CASCADE)
    ACTIVATION_CODE = models.CharField(max_length=6)
    EMAIL = models.EmailField(null=True,blank=True)

ELEARN_BACKEND/STUDENT/forms.py
from django.forms import ModelForm
from .models import STUDENT
from django import forms

class EditStudentForm(ModelForm):
    class Meta:
        model = STUDENT
        fields = ['PASSWORD','FIRST_NAME','LAST_NAME','PICTURE']

ELEARN_BACKEND/STUDENT/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.urls import reverse 
from .models import *
from .forms import *
from HOME_AREA.models import *
from urllib.parse import urlencode
from django.core.cache import cache
from datetime import timedelta
from HOME_AREA.tasks import send_email
# Create your views here.
from ELEARN_BACKEND.CUSTOME_DECORATOR import user_type_required
def update_status(request):
    if request.method == 'POST':
        status = request.POST.get('status')
        cache_key = f'user_status_{request.user.id}'
        cache.set(cache_key, status, timeout=timedelta(days=30).total_seconds())
        return redirect('STUDENTS:Dashboard')

@user_type_required('student')
def Enroll(request,courseName):
    try:
        print("get out")
        student = STUDENT.objects.get(USER_NAME = request.user.USER_NAME)
        course = COURSES.objects.get(COURSE_NAME = courseName)
        print("user found but student adding failed")
        COURSE_LIST.objects.create(course =course, student = student)
        print("success")


    except:
        pass
    return redirect ('HOME_AREA:index')

def Dashboard(request, studentName = ''):
    print(request.user)
    # this approach to serve both personal and others dashboards 
  
    student_name = request.user.USER_NAME if len(studentName) <2  else studentName
    Can_EDIT = True if  request.user.USER_NAME == student_name else False
    print(student_name)
    student = STUDENT.objects.get(USER_NAME = student_name) 
    courses = COURSE_LIST.objects.filter(student = student).values_list('course', flat = True)
    Courses = COURSES.objects.filter(id__in = courses )

    cash_key = f"user_status_{request.user.id}"
    status = cache.get(cash_key)

    return render(request, 'Dashboard.html',{'courses':Courses, 
    'CAN_EDIT':Can_EDIT,'student':student, 'status':status})

@user_type_required('student')
def DropCourse(request, courseName):

    student = STUDENT.objects.get(USER_NAME = request.user)
    print(f'student user name is {student.USER_NAME} and request user is {type(request.user.USER_NAME)}')
    # to ensure same origin so no other student can drop a course that belong to other one 
    if request.user.USER_NAME == student.USER_NAME:
        print('matching passed')
        course = COURSES.objects.get(COURSE_NAME = courseName)
        deleted = COURSE_LIST.objects.get(student = student, course = course)
        deleted.delete()

        return redirect('STUDENTS:Dashboard')
    else:
        return HttpResponseForbidden("you are not authorized to do this")

@user_type_required('student')
def EditProfileLink(request):
   
    return render(request,'EditProfileForm.html')

def EditProfile(request):
    if request.method == 'POST':
        form = EditStudentForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                student = STUDENT.objects.get(USER_NAME = request.user)
                cd = form.cleaned_data
                for key, value in cd.items() :
                    setattr(student, key, value)
                student.save()
                message = "your information updated correctly"
                base_url = reverse('STUDENTS:Dashboard',args=[])
                query_url ={'message':message}
                url_encoded_query = urlencode(query_url)
                full_url = f'{base_url}?{url_encoded_query}'
                return redirect(full_url)
            except:

                return render(request, 'EditProfileForm.html',{'form':form})
        else :
            return render(request, 'EditProfileForm.html',{'form':form})
    else :
        form = EditStudentForm()
        return render(request,'EditProfileForm.html',{'form':form})

@user_type_required('student')
def AddReview(request, courseName):
    if request.method == 'POST':
        opinion = request.POST.get('rev')
        course = COURSES.objects.get(COURSE_NAME = courseName)
        student = STUDENT.objects.get(USER_NAME = request.user)
        review, created = REVIEWS.objects.update_or_create(USER_NAME=student,
                            reviews=course,
                            defaults={'OPINION':opinion}
                            )
        return redirect(reverse('HOME_AREA:Course_Details', args=[courseName]))

    
def RemoveBlockRequest(request, courseName):
    if request.method == 'POST':
        try:
            instruc = COURSES.objects.get(COURSE_NAME = courseName).instructor
            student = STUDENT.objects.get(USER_NAME = request.user).EMAIL
            appeal = request.POST.get('appeal')
            send_email(instruc.EMAIL, appeal)
            send_email(student, f"your message was sent successfully and here is acopy of it {appeal}")
            return redirect('HOME_AREA:index')
        except:
            main_url = reverse('HOME_AREA:Course_Details',args=[courseName])
            return redirect(main_url)

@user_type_required('student')
def AddRating(request, courseName):
    if request.method == 'POST':
        rating = request.POST.get('rate')
        print(rating)
        rate_create = Rating.objects.update_or_create(
            course =COURSES.objects.get(COURSE_NAME = courseName),
            user = STUDENT.objects.get(USER_NAME = request.user),
            defaults={'RATING':rating}
        )
        return redirect(reverse('HOME_AREA:Course_Details',args=[courseName]))







    
    

ELEARN_BACKEND/STUDENT/templates/Dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Dashboard {% endblock %}
{% block main %}
    <div class="space-y-8">
        <!-- Profile Information -->
        <div class="bg-white p-6 rounded-lg shadow-md">
            {% if CAN_EDIT %}
            <h1 class="text-xl font-semibold text-gray-800 mb-4"><a href="{% url 'STUDENTS:EditProfile' %}" class="text-blue-500 hover:text-blue-700">Edit Your Information</a></h1>
            {% endif %}
            <h1 class="text-2xl font-semibold text-gray-800 mb-4">Public Information</h1>
            <p class="text-gray-700 mb-2">Username: {{ student.USER_NAME }}</p>
            <p class="text-gray-700 mb-2">First Name: {{ student.FIRST_NAME }}</p>
            <p class="text-gray-700 mb-2">Last Name: {{ student.LAST_NAME }}</p>
            <img src="{{ student.PICTURE.url }}" alt="profile picture" class="w-32 h-32 rounded-full mt-4" />
        </div>
        <!-- Status Area -->
        <div class="bg-white p-6 rounded-lg shadow-md">
            <h1 class="text-xl font-semibold text-gray-800 mb-4">Status Area</h1>
            {% if CAN_EDIT %}
            <form method="post" action="{% url 'STUDENTS:update_status' %}" class="space-y-4">
                {% csrf_token %}
                <textarea name="status" placeholder="Enter your status" class="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"></textarea>
                <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">Update Status</button>
            </form>
            {% endif %}
            
            {% if status %}
                <p class="mt-4 text-gray-700"> {{ status }}</p>
            {% else %}
                <p class="mt-4 text-gray-500"> No status yet.</p>
            {% endif %}
        </div>

        <!-- Enrolled Courses -->
        <div>
            <h1 class="text-2xl font-semibold text-gray-800 mb-6">Enrolled Courses</h1>
            <div class="space-y-6">
                {% for course in courses %}
                <div class="bg-white p-6 rounded-lg shadow-md">
                    <h2 class="text-xl font-semibold text-gray-800">{{ course.COURSE_NAME }}</h2>
                    <img src="{{ course.COVER_PHOTO.url }}" alt="cover photo" class="w-full h-48 object-cover rounded-md mt-4 mb-6" />
                    {% if CAN_EDIT %}
                    <a href="{% url 'HOME_AREA:Course_Details' course.COURSE_NAME %}" class="text-blue-500 hover:text-blue-700">Resume your learning</a>
                    
                    <a href="{% url 'STUDENTS:DropCourse' course.COURSE_NAME %}" class="ml-4 text-red-500 hover:text-red-700">Drop the course</a>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>



        {% if message %}
        <footer class="bg-gray-100 p-4 rounded-md mt-8">
            <p class="text-center text-gray-600">{{ message }}</p>
        </footer>
        {% endif %}
    </div>
{% endblock %}

ELEARN_BACKEND/STUDENT/templates/EditProfileForm.html
{%extends 'base.html'%}
{% load static%}


{%block title%} edit profile  {%endblock%}
{%block main%}
    <h1> edit your informations</h1>
    <form action="{%url 'STUDENTS:EditProfile'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {% if form%}
        {{form}}
        {%else%}
        <p> no form recieved</p>
        {%endif%}
        <input type="submit" value="submit" />
    </form>
{%endblock%}

ELEARN_BACKEND/STUDENT/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    student page
</body>
</html>