ELEARN_BACKEND/ELEARN_BACKEND/urls.py
from django.contrib import admin
from django.urls import path, include  
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path('admin/', admin.site.urls),
   
    path('student/',include('STUDENT.urls')),
    path('instructor/',include('INSTRUCTOR.urls')),
    path('',include('HOME_AREA.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path("__reload__/", include("django_browser_reload.urls")), # for refresh tailwind 
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ELEARN_BACKEND/HOME_AREA/urls.py
from django.urls import path 
from . import views, forms, REGLOG, APIs
app_name ='HOME_AREA'
urlpatterns = [
   #registeration, log in functionalities
    path('INSTRUCTOR_REG',REGLOG.instructor_reg_form, name="instructor_reg_form"),
    path('INSTRUCTOR_LOG',REGLOG.instructor_login , name ="instructor_login"),
    path('STUDENT_REG', REGLOG.student_reg_form, name="student_reg_form"),
    path('STUDENT_LOG',REGLOG.student_login, name ="student_login"),
    path("VERIFICATION/<str:user_type>",REGLOG.Verify , name="Verify" ),
    path("forget/<str:user_type>",REGLOG.Forget , name="Forget" ),
    path("logout",REGLOG.Logout, name='Logout'),
    path("editpass/<str:user_type>",REGLOG.EditPass, name='EditPass'),
    path('AccessChatRoom/<str:courseName>/<str:userCat>', views.AccessChatRoom , name = 'AccessChatRoom'),
    path('SaveChats/', views.SaveTOchat, name = 'SaveTOchat'),
    #api views
    path('courses/', APIs.CourseListView.as_view(), name='course-list'),
    path('courses/<str:courseName>/', APIs.CourseDetailsFullView.as_view(), name='course-details-full'),
    path('courses/general/<str:courseName>/', APIs.CourseDetailsGeneralView.as_view(), name='course-details-general'),



    #courses functionalities
    path("Course_Details/<str:courseName>",views.Course_Details, name= 'Course_Details'),
    path('',views.index , name ="index"),



]

ELEARN_BACKEND/INSTRUCTOR/urls.py
from django.urls import path
from . import views, APIs

app_name ='instructor'
urlpatterns = [
    path('CourseDetails/<str:courseName>',views.CourseDetails, name='CourseDetails'),
    path('Dashboard/',views.Dashboard, name='Dashboard'),
    path('CreateCourse',views.CreateCourse, name='CreateCourse'),
    path('course/<str:courseName>/',views.CourseDetailView.as_view(), name='course_detail'),
    path('course/<str:courseName>/delete/',views.CourseDeleteView.as_view(), name='course_delete'),
    path('Block', views.Block, name = 'Block'),
    path('UnBlock', views.UnBlock, name = 'UnBlock'),
    path('AddLecture/<str:courseName>', views.AddLecture, name = 'AddLecture'),
    path('HandlLectures/<str:courseName>', views.HandlLectures, name = 'HandlLectures'),
    path('Publish/<str:courseName>/', views.Publish, name = 'Publish'),
    path('Learners', views.LearnersList.as_view(), name = 'Learners'),
    path('update_status',views.update_status, name = 'update_status'),
    path('SendToFollowers/<str:courseName>', views.SendToFollowers, name = 'SendToFollowers'),
    path('DeleteLecture/<str:courseName>/<str:lectureName>', views.LectureDeleteView.as_view(), name = 'DeleteLecture'),
    #APIS
    path('APIs/InstructorLogAPI', APIs.InstructorLogAPI.as_view(), name = 'InstructorLogAPI'),
    path('APIs/InstrucotReg', APIs.InstrucotReg.as_view(), name = 'InstrucotReg'),
    path('APIs/InstructorAPI/<str:USER_NAME>', APIs.InstructorAPI.as_view(), name = 'InstructorAPI'),
    path('APIs/CourseCRUDAPI/<int:pk>', APIs.CourseCRUDAPI.as_view()),
    path('APIs/LecturesCRUDsAPI/<str:course__COURSE_NAME>', APIs.LecturesCRUDsAPI.as_view()),
    path('APIS/UNBlockHandlerAPI', APIs.UNBlockHandlerAPI, name = 'UNBlockHandlerAPI'),
    path('APIS/BlookHandlerAPI', APIs.BlookHandlerAPI, name = 'BlookHandlerAPI'),
    path('',views.index, name='index')
]

"""
    path('EditCourse/<str:courseName', views.EditCourse, name ='EditCourse'),
    path('DeleteCourse/<str:courseName', views.DeleteCourse, name = 'DeleteCourse'),
    path('ViewCourse/<str:courseName>', views.ViewCourse, name = 'ViewCourse'),
"""

ELEARN_BACKEND/STUDENT/urls.py
from django.urls import path
from . import views , APIs
# declaring namespace so i can use these views from anywhere 
app_name = 'STUDENTS'
urlpatterns = [
    #dashboard area
    path('Dashboard/<str:studentName>', views.Dashboard, name = 'DashboardWithUserName'),
    path('Dashboard', views.Dashboard, name = 'Dashboard'),

    path('DropCourse/<str:courseName>', views.DropCourse, name = 'DropCourse'),
    path('EditProfileLink',views.EditProfileLink , name = 'EditProfileLink'),
    path('EditProfile',views.EditProfile, name = 'EditProfile'),
    path('update-status/', views.update_status, name='update_status'),
    path('AddReview/<str:courseName>', views.AddReview, name = 'AddReview'),
    path('RemoveBlockRequest/<str:courseName>',views.RemoveBlockRequest, name = 'RemoveBlockRequest'),
    path('AddRating/<str:courseName>', views.AddRating, name = 'AddRating'),

    path('enrol/<str:courseName>/', views.Enroll, name='Enroll'),  # Make sure there is a trailing slash

    #student APIs area################
    path('APIs/Forms/ForgetPassStudentAPI',APIs.ForgetPassStudentAPI.as_view(), name = 'ForgetPassStudentAPI'),
    path('APIs/Forms/VerifyStudentAPI',APIs.VerifyStudentAPI.as_view(), name = 'VerifyStudentAPI'),
    path('APIs/Forms/StudentLogAPI',APIs.StudentLogAPI.as_view(), name = 'StudentLogAPI'),
    path('APIs/Forms/StudentReg',APIs.StudentReg.as_view()),
    path('APIs/<str:course__COURSE_NAME>',APIs.COURSE_student_APIs.as_view()),
    # to avoid collision with the above url
    path('API/<str:USER_NAME>', APIs.StudentApi.as_view()),
   


]

ELEARN_BACKEND/INSTRUCTOR/forms.py
from django.forms import ModelForm
from HOME_AREA.models import COURSES, LECTURES
from django import forms
class CreateForm(ModelForm):

    class Meta:
        model = COURSES
        exclude= ["instructor","RATING"]
class AddLectureForm(ModelForm):

    class Meta:
        model = LECTURES
        exclude = ['course']

class BlockForm(forms.Form):
    BLOCKED_USER = forms.CharField(max_length=50)

ELEARN_BACKEND/STUDENT/forms.py
from django.forms import ModelForm
from .models import STUDENT
from django import forms

class EditStudentForm(ModelForm):
    class Meta:
        model = STUDENT
        fields = ['PASSWORD','FIRST_NAME','LAST_NAME','PICTURE']

ELEARN_BACKEND/HOME_AREA/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.http import JsonResponse
from .tasks import send_email ,CleanDatabase
from django.views.decorators.csrf import csrf_exempt
import json
#to save generated code in corresponding database class
from INSTRUCTOR.models import CODE_GENERATOR_INSTR, INSTRUCTOR, BLOCK_LIST
from STUDENT.models import CODE_GENERATOR, STUDENT, COURSE_LIST
from random import randint
from django.contrib.auth.models import AnonymousUser
# using auth to save log ing sessions 
from django.contrib.auth.models import User
from django.contrib.auth import login, logout , authenticate
from .AuthCust import *
from django.urls import reverse 
from django.db.models import Avg
from django.utils import timezone
from datetime import timedelta
from django.contrib.contenttypes.models import ContentType

# Create your views here.
#home page will produce all courses and wil have pagination and other things (landing page)
def index(request):
    user = request.user if str(request.user) != "AnonymousUser" else False
   

    courses = COURSES.objects.all()
    #create average rating 
    courseDict={}
    for course in courses:
        avg_rate = course.rating_set.aggregate(Avg('RATING')).get('RATING__avg')
        print(f'avg_rate {avg_rate}')
        total_raters = course.rating_set.all().count()
        print(total_raters)
        courseDict[course] = [avg_rate if avg_rate != None else 0,total_raters]
        print(courseDict[course])
    return render (request , 'index.html',{'courses':courseDict, "user":user})
# in this method we display the course details and if user is enrolled or not 
def Course_Details(request, courseName):
    course = COURSES.objects.get(COURSE_NAME = courseName)
    reviews = REVIEWS.objects.filter(reviews = course)
    lectures = course.lectures.all()

    print(f'request.user is {request.user}')
    if isinstance(request.user, AnonymousUser):
        print("we are anonymous")
        return render(request, "CourseDetails.html", {
            'course': course,
            'lectures': lectures,
            'reviews': reviews,
            'enrolled': False,
            'blocked': False,
            'user_cat': False
        })
    
    elif request.user.user_cat == 'instructor' and course.instructor.USER_NAME != request.user.USER_NAME:
            # constructing the path using reverse dynamically
        return redirect(reverse('instructor:CourseDetails',args=[courseName]))
    WatcherName = request.user.USER_NAME
    user_cat = request.user.user_cat

    #if student is blocked cannot access the courses belong to that instructor and need to contact him
    if WatcherName and user_cat == 'student' :
        student = STUDENT.objects.get(USER_NAME = WatcherName)
        Blocked = BLOCK_LIST.objects.filter(students = student, instructors=course.instructor).exists()
        
        IsEnrolled =  COURSE_LIST.objects.filter(course = course, student = student).exists()
    elif WatcherName and user_cat == 'instructor':
        IsEnrolled = True
        Blocked = False
    return render(request, "CourseDetails.html", {'course':course,
                'lectures':lectures, 'reviews':reviews, 
                'enrolled':IsEnrolled, 'blocked':Blocked , 'user_cat':user_cat})

def AccessChatRoom(request, courseName, userCat):
    user_name = request.user.USER_NAME
    course = COURSES.objects.get(COURSE_NAME = courseName)

    #getting all chat related to that course 
    two_weeks_ago = timezone.now() - timedelta(days=14)
    # to fixchannel group name that refuse to contain spaces 
    cour = courseName.split(' ')
    cc= ""
    for co in cour:
        cd = co.strip()
        cc+=cd

    chats = ChatRoom.objects.filter(courseRoom = course, TimeStamp__gte = two_weeks_ago)
        
    return render(request, 'CourseChatRoom.html',
                            {'course':cc,
                            'user':request.user, 
                            'userName':user_name, 
                            'chats':chats,
                            'userCat':userCat,
                            'coursy':courseName})
@csrf_exempt
def SaveTOchat(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        print(data)
        message = data["message"]
        # here creating a way so we can add student or instructor to the chat database under same field sender
        userName = STUDENT.objects.get(USER_NAME = data["userName"]) if data['userCat'] =='student' else INSTRUCTOR.objects.get(USER_NAME = data["userName"])
        content = ContentType.objects.get_for_model(STUDENT) if  data['userCat'] =='student' else ContentType.objects.get_for_model(INSTRUCTOR)
        course = COURSES.objects.get(COURSE_NAME = data["course"])
        #kicking the bad user out of the chat immediately
        if BLOCK_LIST.objects.filter(students = userName, instructors = course.instructor).exists():
            return redirect('HOME_AREA:index')
        ChatRoom.objects.create(message = message, courseRoom = course, 
                                object_id = userName.id,
                                content_type = content)
        return JsonResponse({'status': 'success'})
    return JsonResponse({'status': 'failed', 'error': 'Invalid request method'})

ELEARN_BACKEND/STUDENT/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.urls import reverse 
from .models import *
from .forms import *
from HOME_AREA.models import *
from urllib.parse import urlencode
from django.core.cache import cache
from datetime import timedelta
from HOME_AREA.tasks import send_email
# Create your views here.
from ELEARN_BACKEND.CUSTOME_DECORATOR import user_type_required
def update_status(request):
    if request.method == 'POST':
        status = request.POST.get('status')
        cache_key = f'user_status_{request.user.id}'
        cache.set(cache_key, status, timeout=timedelta(days=30).total_seconds())
        return redirect('STUDENTS:Dashboard')

@user_type_required('student')
def Enroll(request,courseName):
    try:
        print("get out")
        student = STUDENT.objects.get(USER_NAME = request.user.USER_NAME)
        course = COURSES.objects.get(COURSE_NAME = courseName)
        print("user found but student adding failed")
        COURSE_LIST.objects.create(course =course, student = student)
        print("success")


    except:
        pass
    return redirect ('HOME_AREA:index')

def Dashboard(request, studentName = ''):
    print(request.user)
    # this approach to serve both personal and others dashboards 
  
    student_name = request.user.USER_NAME if len(studentName) <2  else studentName
    Can_EDIT = True if  request.user.USER_NAME == student_name else False
    print(student_name)
    student = STUDENT.objects.get(USER_NAME = student_name) 
    courses = COURSE_LIST.objects.filter(student = student).values_list('course', flat = True)
    Courses = COURSES.objects.filter(id__in = courses )

    cash_key = f"user_status_{request.user.id}"
    status = cache.get(cash_key)

    return render(request, 'Dashboard.html',{'courses':Courses, 
    'CAN_EDIT':Can_EDIT,'student':student, 'status':status})

@user_type_required('student')
def DropCourse(request, courseName):

    student = STUDENT.objects.get(USER_NAME = request.user)
    print(f'student user name is {student.USER_NAME} and request user is {type(request.user.USER_NAME)}')
    # to ensure same origin so no other student can drop a course that belong to other one 
    if request.user.USER_NAME == student.USER_NAME:
        print('matching passed')
        course = COURSES.objects.get(COURSE_NAME = courseName)
        deleted = COURSE_LIST.objects.get(student = student, course = course)
        deleted.delete()

        return redirect('STUDENTS:Dashboard')
    else:
        return HttpResponseForbidden("you are not authorized to do this")

@user_type_required('student')
def EditProfileLink(request):
   
    return render(request,'EditProfileForm.html')

def EditProfile(request):
    if request.method == 'POST':
        form = EditStudentForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                student = STUDENT.objects.get(USER_NAME = request.user)
                cd = form.cleaned_data
                for key, value in cd.items() :
                    setattr(student, key, value)
                student.save()
                message = "your information updated correctly"
                base_url = reverse('STUDENTS:Dashboard',args=[])
                query_url ={'message':message}
                url_encoded_query = urlencode(query_url)
                full_url = f'{base_url}?{url_encoded_query}'
                return redirect(full_url)
            except:

                return render(request, 'EditProfileForm.html',{'form':form})
        else :
            return render(request, 'EditProfileForm.html',{'form':form})
    else :
        form = EditStudentForm()
        return render(request,'EditProfileForm.html',{'form':form})

@user_type_required('student')
def AddReview(request, courseName):
    if request.method == 'POST':
        opinion = request.POST.get('rev')
        course = COURSES.objects.get(COURSE_NAME = courseName)
        student = STUDENT.objects.get(USER_NAME = request.user)
        review, created = REVIEWS.objects.update_or_create(USER_NAME=student,
                            reviews=course,
                            defaults={'OPINION':opinion}
                            )
        return redirect(reverse('HOME_AREA:Course_Details', args=[courseName]))

    
def RemoveBlockRequest(request, courseName):
    if request.method == 'POST':
        try:
            instruc = COURSES.objects.get(COURSE_NAME = courseName).instructor
            student = STUDENT.objects.get(USER_NAME = request.user).EMAIL
            appeal = request.POST.get('appeal')
            send_email(instruc.EMAIL, appeal)
            send_email(student, f"your message was sent successfully and here is acopy of it {appeal}")
            return redirect('HOME_AREA:index')
        except:
            main_url = reverse('HOME_AREA:Course_Details',args=[courseName])
            return redirect(main_url)

@user_type_required('student')
def AddRating(request, courseName):
    if request.method == 'POST':
        rating = request.POST.get('rate')
        print(rating)
        rate_create = Rating.objects.update_or_create(
            course =COURSES.objects.get(COURSE_NAME = courseName),
            user = STUDENT.objects.get(USER_NAME = request.user),
            defaults={'RATING':rating}
        )
        return redirect(reverse('HOME_AREA:Course_Details',args=[courseName]))







    
    

ELEARN_BACKEND/HOME_AREA/templates/CourseDetails.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Course Details {% endblock %}

{% block main %}
<div class="container mx-auto py-8">
    {% if blocked %}
    <div class="bg-red-100 text-red-700 p-6 rounded-lg shadow-md">
        <p>
            You have been blocked from accessing this course by the instructor. 
            You can send a message to resolve the issue.
        </p>
        <form action="{% url 'STUDENTS:RemoveBlockRequest' course.COURSE_NAME %}" method="post" class="mt-4">
            {% csrf_token %}
            <label for="appeal" class="block text-sm font-medium text-gray-700">Write your appeal</label>
            <textarea name="appeal" placeholder="Talk to your instructor" rows="4" class="mt-1 block w-full p-2 border border-gray-300 rounded-md"></textarea>
            <button type="submit" value="submit" class="mt-3 inline-flex items-center px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700">Submit</button>
        </form>
        {% if message %}
        <div class="mt-4 text-green-600">{{ message }}</div>
        {% endif %}
    </div>
    {% else %}
    <div>
        <h1 class="text-3xl font-bold text-gray-900 mb-6">{{ course.COURSE_NAME }}</h1>
        <video id="LECTURE" controls class="w-full h-auto rounded-lg shadow-md"></video>
        <div class="mt-8">
            {% for lecture in lectures %}
            <div class="mb-4">
                {% if enrolled %}
                    {% if lecture.VIDEO %}
                    <a href="#" onclick="display('{{ lecture.VIDEO.url }}'); return false;" class="text-blue-600 hover:text-blue-800">{{ lecture.NAME }}</a><br>
                        {% if lecture.ADDITIONAL_FILES %}
                        <a href="{{ lecture.ADDITIONAL_FILES.url }}" download class="text-sm text-gray-600 hover:text-gray-800">{{ lecture.ADDITIONAL_FILES.name }}</a>
                        {% endif %}
                    {% endif %}
                {% else %}
                <h2 class="text-lg font-semibold text-gray-800">{{ lecture.NAME }}</h2>
                {% endif %}
            </div>
            {% endfor %}
        </div>

        <div class="mt-8">
            {% if reviews %}
            <h3 class="text-xl font-bold text-gray-900">Reviews</h3>
            <div class="mt-4 space-y-4">
                {% for review in reviews %}
                <div class="p-4 bg-gray-100 rounded-lg shadow-md">
                    <p><a href="{%url 'STUDENTS:DashboardWithUserName' review.USER_NAME%}" class="text-blue-600 hover:text-blue-800">{{ review.USER_NAME }}:</a> {{ review.OPINION }}</p>
                    <p class="text-sm text-gray-500">{{ review.WRITING_DATE }}</p>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <p class="text-gray-600">No reviews for this course yet.</p>
            {% endif %}
        </div>

        <div class="mt-8">
            {% if enrolled  and user_cat %}
            <div class="p-6 bg-green-100 text-green-800 rounded-lg shadow-md">
                <p>You are enrolled in this course. Enjoy learning!</p>
                <form action="{% url 'STUDENTS:AddReview' course.COURSE_NAME %}" method="post" class="mt-4">
                    {% csrf_token %}
                    <label for="rev" class="block text-sm font-medium text-gray-700">Share your opinion about the course:</label>
                    <input type="text" name="rev" class="mt-1 block w-full p-2 border border-gray-300 rounded-md" />
                    <button type="submit" value="submit" class="mt-3 inline-flex items-center px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700">Submit</button>
                </form>
            </div>

            <div class="mt-8 p-6 bg-yellow-100 text-yellow-800 rounded-lg shadow-md">
                <p>How would you rate the course?</p>
                <form action="{% url 'STUDENTS:AddRating' course.COURSE_NAME %}" method="post" class="mt-4">
                    {% csrf_token %}
                    <label for="rate" class="block text-sm font-medium text-gray-700">Rate the course</label>
                    <select name="rate" class="mt-1 block w-full p-2 border border-gray-300 rounded-md">
                        <option value=1>1 star</option>
                        <option value=2>2 stars</option>
                        <option value=3>3 stars</option>
                        <option value=4>4 stars</option>
                        <option value=5>5 stars</option>
                    </select>
                    <button type="submit" value="submit" class="mt-3 inline-flex items-center px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700">Submit</button>
                </form>

            </div>
            <div>
                
                <a href="{%url 'HOME_AREA:AccessChatRoom' course.COURSE_NAME user_cat %}" target="_blank">chat with other enrolled students</a>
                
            </div>

            {% else %}
            <div class="mt-8 p-6 bg-gray-100 text-gray-800 rounded-lg shadow-md">
                <p><a href="{% url 'STUDENTS:Enroll' course.COURSE_NAME %}" class="text-blue-600 hover:text-blue-800">Enroll now so you can watch the lectures and chat with other students</a></p>
            </div>
            {% endif %}
        </div>
    </div>
    {% endif %}
</div>



<script>

    let videoElement = document.getElementById("LECTURE");
 

    function display(url) {
        videoElement.src = url;
        videoElement.play();
    }
</script>
{% endblock %}

ELEARN_BACKEND/HOME_AREA/templates/editpassword.html
{%extends 'base.html'%}
{% load static%}


{%block title%} edit password {%endblock%}
{%block main%}
    <form action="{% url 'HOME_AREA:EditPass' user_type=user_type%}" method="post">
        {%csrf_token%}
        {{form}}
        {%if message%}
        {{message}}
        {%endif%}
        <input type="submit" value="submit">
    </form>
{%endblock%}

ELEARN_BACKEND/HOME_AREA/templates/forget.html
{%extends 'base.html'%}
{% load static%}


{%block title%} forget password {%endblock%}
{%block main%}
    <form action="{% url 'HOME_AREA:Forget' user_type=user_type %}" method="post">
    
    {%csrf_token%}
    {{form}}
    <input type="submit" value="submit"/>
    </form>
{%endblock%}

ELEARN_BACKEND/HOME_AREA/templates/instr_login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Instructor Log In {% endblock %}

{% block main %}
<div class="flex justify-center items-center min-h-screen bg-gray-50">
    <div class="w-full max-w-md p-8 bg-white rounded-lg shadow-md">
        <h2 class="text-2xl font-bold text-gray-800 mb-6 text-center">Instructor Log In</h2>
        <form action="{% url 'HOME_AREA:instructor_login' %}" method="post" class="space-y-6">
            {% csrf_token %}
            <div class="space-y-4">
                {{ form.as_p }}
            </div>
            {% if message %}
            <div class="text-red-600 text-sm">{{ message }}</div>
            {% endif %}
            {% if alarm %}
            <div class="text-yellow-600 text-sm mb-4">
                {{ alarm }}
                <a href="{% url 'HOME_AREA:Verify' user_type='instructor' %}" class="text-blue-600 hover:text-blue-800">
                    Click here to activate your account (check your inbox or junk folder for the code).
                </a>
            </div>
            {% endif %}
            <div class="flex justify-between items-center">
                <a href="{% url 'HOME_AREA:Forget' user_type='instructor' %}" class="text-sm text-blue-600 hover:text-blue-800">Forgot your password?</a>
                <button type="submit" class="inline-flex items-center px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700">
                    Submit
                </button>
            </div>
        </form>
        <div class="mt-6 text-center">
            <a href="{% url 'HOME_AREA:instructor_reg_form' %}" class="text-sm text-blue-600 hover:text-blue-800">
                Don't have an account? Register now
            </a>
        </div>
    </div>
</div>
{% endblock %}

ELEARN_BACKEND/HOME_AREA/templates/instructorForm.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Instructor Registration {% endblock %}

{% block main %}
<div class="flex justify-center items-center min-h-screen bg-gray-50">
    <div class="w-full max-w-lg p-8 bg-white rounded-lg shadow-md">
        <h1 class="text-2xl font-bold text-gray-800 mb-6 text-center">Instructor Registration Form</h1>
        <form action="{% url 'HOME_AREA:instructor_reg_form' %}" method="post" enctype="multipart/form-data" class="space-y-6">
            {% csrf_token %}
            <div class="space-y-4">
                {{ form.as_p }}
            </div>
            <div class="flex justify-center">
                <button type="submit" class="px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700">
                    Submit
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

ELEARN_BACKEND/HOME_AREA/templates/student_login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Learner Login {% endblock %}

{% block main %}
<div class="flex justify-center items-center min-h-screen bg-gray-50">
    <div class="w-full max-w-md p-8 bg-white rounded-lg shadow-md">
        <h2 class="text-2xl font-bold text-gray-800 mb-6 text-center">Learner Login</h2>
        <form action="{% url 'HOME_AREA:student_login' %}" method="post" class="space-y-6">
            {% csrf_token %}
            <div class="space-y-4">
                {{ form.as_p }}
            </div>
            {% if message %}
            <div class="text-red-600 text-sm">{{ message }}</div>
            {% endif %}
            {% if alarm %}
            <div class="text-yellow-600 text-sm mb-4">
                {{ alarm }}
                <a href="{% url 'HOME_AREA:Verify' user_type='student' %}" class="text-blue-600 hover:text-blue-800">
                    Click here to activate your account (check your inbox or junk folder for the code).
                </a>
            </div>
            {% endif %}
            <div class="flex justify-between items-center">
                <a href="{% url 'HOME_AREA:Forget' user_type='student' %}" class="text-sm text-blue-600 hover:text-blue-800">Forgot your password?</a>
                <button type="submit" class="inline-flex items-center px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700">
                    Submit
                </button>
            </div>
        </form>
        <div class="mt-6 text-center">
            <a href="{% url 'HOME_AREA:student_reg_form' %}" class="text-sm text-blue-600 hover:text-blue-800">
                Don't have an account? Register now
            </a>
        </div>
    </div>
</div>
{% endblock %}