ELEARN_BACKEND/ELEARN_BACKEND/urls.py
from django.contrib import admin
from django.urls import path, include  
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path('admin/', admin.site.urls),
   
    path('student/',include('STUDENT.urls')),
    path('instructor/',include('INSTRUCTOR.urls')),
    path('',include('HOME_AREA.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path("__reload__/", include("django_browser_reload.urls")), # for refresh tailwind 
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ELEARN_BACKEND/HOME_AREA/urls.py
from django.urls import path 
from . import views, forms, REGLOG, APIs
app_name ='HOME_AREA'
urlpatterns = [
   #registeration, log in functionalities
    path('INSTRUCTOR_REG',REGLOG.instructor_reg_form, name="instructor_reg_form"),
    path('INSTRUCTOR_LOG',REGLOG.instructor_login , name ="instructor_login"),
    path('STUDENT_REG', REGLOG.student_reg_form, name="student_reg_form"),
    path('STUDENT_LOG',REGLOG.student_login, name ="student_login"),
    path("VERIFICATION/<str:user_type>",REGLOG.Verify , name="Verify" ),
    path("forget/<str:user_type>",REGLOG.Forget , name="Forget" ),
    path("logout",REGLOG.Logout, name='Logout'),
    path("editpass/<str:user_type>",REGLOG.EditPass, name='EditPass'),
    path('AccessChatRoom/<str:courseName>/<str:userCat>', views.AccessChatRoom , name = 'AccessChatRoom'),
    path('SaveChats/', views.SaveTOchat, name = 'SaveTOchat'),
    #api views
    path('courses/', APIs.CourseListView.as_view(), name='course-list'),
    path('courses/<str:courseName>/', APIs.CourseDetailsFullView.as_view(), name='course-details-full'),
    path('courses/general/<str:courseName>/', APIs.CourseDetailsGeneralView.as_view(), name='course-details-general'),



    #courses functionalities
    path("Course_Details/<str:courseName>",views.Course_Details, name= 'Course_Details'),
    path('',views.index , name ="index"),



]

ELEARN_BACKEND/INSTRUCTOR/urls.py
from django.urls import path
from . import views, APIs

app_name ='instructor'
urlpatterns = [
    path('CourseDetails/<str:courseName>',views.CourseDetails, name='CourseDetails'),
    path('Dashboard/',views.Dashboard, name='Dashboard'),
    path('CreateCourse',views.CreateCourse, name='CreateCourse'),
    path('course/<str:courseName>/',views.CourseDetailView.as_view(), name='course_detail'),
    path('course/<str:courseName>/delete/',views.CourseDeleteView.as_view(), name='course_delete'),
    path('Block', views.Block, name = 'Block'),
    path('UnBlock', views.UnBlock, name = 'UnBlock'),
    path('AddLecture/<str:courseName>', views.AddLecture, name = 'AddLecture'),
    path('HandlLectures/<str:courseName>', views.HandlLectures, name = 'HandlLectures'),
    path('Publish/<str:courseName>/', views.Publish, name = 'Publish'),
    path('Learners', views.LearnersList.as_view(), name = 'Learners'),
    path('update_status',views.update_status, name = 'update_status'),
    path('SendToFollowers/<str:courseName>', views.SendToFollowers, name = 'SendToFollowers'),
    path('DeleteLecture/<str:courseName>/<str:lectureName>', views.LectureDeleteView.as_view(), name = 'DeleteLecture'),
    #APIS
    path('APIs/InstructorLogAPI', APIs.InstructorLogAPI.as_view(), name = 'InstructorLogAPI'),
    path('APIs/InstrucotReg', APIs.InstrucotReg.as_view(), name = 'InstrucotReg'),
    path('APIs/InstructorAPI/<str:USER_NAME>', APIs.InstructorAPI.as_view(), name = 'InstructorAPI'),
    path('APIs/CourseCRUDAPI/<int:pk>', APIs.CourseCRUDAPI.as_view()),
    path('APIs/LecturesCRUDsAPI/<str:course__COURSE_NAME>', APIs.LecturesCRUDsAPI.as_view()),
    path('APIS/UNBlockHandlerAPI', APIs.UNBlockHandlerAPI, name = 'UNBlockHandlerAPI'),
    path('APIS/BlookHandlerAPI', APIs.BlookHandlerAPI, name = 'BlookHandlerAPI'),
    path('',views.index, name='index')
]

"""
    path('EditCourse/<str:courseName', views.EditCourse, name ='EditCourse'),
    path('DeleteCourse/<str:courseName', views.DeleteCourse, name = 'DeleteCourse'),
    path('ViewCourse/<str:courseName>', views.ViewCourse, name = 'ViewCourse'),
"""

ELEARN_BACKEND/STUDENT/urls.py
from django.urls import path
from . import views , APIs
# declaring namespace so i can use these views from anywhere 
app_name = 'STUDENTS'
urlpatterns = [
    #dashboard area
    path('Dashboard/<str:studentName>', views.Dashboard, name = 'DashboardWithUserName'),
    path('Dashboard', views.Dashboard, name = 'Dashboard'),

    path('DropCourse/<str:courseName>', views.DropCourse, name = 'DropCourse'),
    path('EditProfileLink',views.EditProfileLink , name = 'EditProfileLink'),
    path('EditProfile',views.EditProfile, name = 'EditProfile'),
    path('update-status/', views.update_status, name='update_status'),
    path('AddReview/<str:courseName>', views.AddReview, name = 'AddReview'),
    path('RemoveBlockRequest/<str:courseName>',views.RemoveBlockRequest, name = 'RemoveBlockRequest'),
    path('AddRating/<str:courseName>', views.AddRating, name = 'AddRating'),

    path('enrol/<str:courseName>/', views.Enroll, name='Enroll'),  # Make sure there is a trailing slash

    #student APIs area################
    path('APIs/Forms/ForgetPassStudentAPI',APIs.ForgetPassStudentAPI.as_view(), name = 'ForgetPassStudentAPI'),
    path('APIs/Forms/VerifyStudentAPI',APIs.VerifyStudentAPI.as_view(), name = 'VerifyStudentAPI'),
    path('APIs/Forms/StudentLogAPI',APIs.StudentLogAPI.as_view(), name = 'StudentLogAPI'),
    path('APIs/Forms/StudentReg',APIs.StudentReg.as_view()),
    path('APIs/<str:course__COURSE_NAME>',APIs.COURSE_student_APIs.as_view()),
    # to avoid collision with the above url
    path('API/<str:USER_NAME>', APIs.StudentApi.as_view()),
   


]

ELEARN_BACKEND/INSTRUCTOR/models.py
from django.db import models
from django.core.validators import MinLengthValidator, RegexValidator

#Create your models here.
class INSTRUCTOR(models.Model):
    FIRST_NAME = models.CharField(max_length=50 , null=False , blank=False)
    LAST_NAME = models.CharField(max_length=50 , null=False , blank=False)
    USER_NAME = models.CharField(max_length=50 , null=False , blank=False, unique=True)
    EMAIL = models.EmailField(null=False , blank=False, unique=True)
    last_login = models.DateTimeField(null=True, blank=True)  # Add last_login field

    PHONE = models.CharField(max_length=15 , null=False, blank=False, unique=True)
    PASSWORD = models.CharField(null=False, blank=False, max_length=12,
     validators=[
            MinLengthValidator(8),  # Minimum length of 8 characters
            RegexValidator(
                regex=r'^(?=.*[a-z])(?=.*\d)[a-zA-Z\d]{8,}$',
                message="Password must contain at least one lowercase letter and one digit.",
            ),
        ]
    )
    PICTURE = models.ImageField(upload_to="images/", null=False, blank=False) #optioanl pic
    block_list = models.ManyToManyField('STUDENT.STUDENT', through='BLOCK_LIST')
    is_active = models.BooleanField(default = True)
    Isactive = models.BooleanField(default = False)
    def __str__(self):
        return self.USER_NAME
    
    @property
    def user_cat(self):
        return "instructor"

    class META:
        verbose_name_plural = "Instructors"
        permissions = [
            ("BLOCK_STUDENT","ADD_LECTURES","VIEW_STUDENTS","DELETE_COURSE","SEND_MAIL")
        ]
class BLOCK_LIST(models.Model):
    students = models.ForeignKey('STUDENT.STUDENT',  on_delete=models.DO_NOTHING , related_name="students")
    instructors = models.ForeignKey(INSTRUCTOR,  on_delete=models.DO_NOTHING, related_name="instructors")
#table to generate code and email to verify user to complete (registeration, update password, delete account)(prevent bots)
class CODE_GENERATOR_INSTR(models.Model):
    USER_VERIFIER = models.ForeignKey('INSTRUCTOR', on_delete=models.CASCADE)
    ACTIVATION_CODE = models.CharField(max_length=6)
    EMAIL = models.EmailField(null=True,blank=True)

ELEARN_BACKEND/INSTRUCTOR/forms.py
from django.forms import ModelForm
from HOME_AREA.models import COURSES, LECTURES
from django import forms
class CreateForm(ModelForm):

    class Meta:
        model = COURSES
        exclude= ["instructor","RATING"]
class AddLectureForm(ModelForm):

    class Meta:
        model = LECTURES
        exclude = ['course']

class BlockForm(forms.Form):
    BLOCKED_USER = forms.CharField(max_length=50)

ELEARN_BACKEND/INSTRUCTOR/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, UpdateView, DeleteView, ListView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse
from HOME_AREA.models import COURSES, LECTURES
from STUDENT.models import COURSE_LIST, STUDENT
from .models import *
from .forms import *
from HOME_AREA.tasks import send_email
from ELEARN_BACKEND.CUSTOME_DECORATOR import *
from django.core.cache import cache
from datetime import timedelta
# Create your views here.
def index(request):
    user = request.user if str(request.user) != "AnonymousUser" else False
    print(f'user is {request.user.user_cat}')

    courses = COURSES.objects.all()
    return render (request , 'index.html',{'courses':courses, "user":user})

def CourseDetails(request, courseName):

    course = COURSES.objects.get(COURSE_NAME = courseName)
    lectures = course.lectures.all()
    return render(request, 'course-details.html',{'course':course,'lectures':lectures})

def update_status(request):
    if request.method == 'POST':
        status = request.POST.get('status')
        cache_key = f'user_status_{request.user.id}'
        cache.set(cache_key, status, timeout=timedelta(days=30).total_seconds())
        return redirect('instructor:Dashboard')


#show his courses to edit any as links
# number of enrolled students per course
#ability to send email to course enrolled -> another function =link inside dashboard
#authenticate the user as instructor
class InstructorRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return  self.request.user.user_cat == 'instructor'

    def handle_no_permission(self):
        raise Http404  
#view students
class LearnersList(InstructorRequiredMixin, ListView): 
    model = STUDENT
    template_name = 'LearnersList.html'
    context_object_name = 'learners'

    def get_queryset(self):
        learners = {}
        instru = INSTRUCTOR.objects.get(USER_NAME=self.request.user)  # Use self.request.user
        courses = COURSES.objects.filter(instructor=instru)
        
        for course in courses:
            course_students = COURSE_LIST.objects.filter(course=course)
            student_list = [cs.student for cs in course_students] 
            learners[course] = student_list
        
        return learners

# View a Course
class CourseDetailView(InstructorRequiredMixin, DetailView):
    model = COURSES
    template_name = 'course_detail.html'
    context_object_name = 'course'
    #needed to override so i can search by course name  useless pain 
    def get_object(self, queryset=None):
        # Fetch the course by COURSE_NAME instead of pk or slug
        courseName = self.kwargs.get('courseName')
        return COURSES.objects.get(COURSE_NAME=courseName)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = self.get_object()
        lectures = LECTURES.objects.filter(course = course)
        print(lectures)
        context['courseLectures'] = lectures
        return context

class CourseDeleteView(InstructorRequiredMixin, DeleteView):
    model = COURSES
    template_name = 'course_confirm_delete.html'
    context_object_name = 'course'

    def get_object(self, queryset=None):
        return COURSES.objects.get(COURSE_NAME=self.kwargs['courseName'])

    def get_success_url(self):
        return redirect('instructor:Dashboard') 
#deleting lecture 
class LectureDeleteView(InstructorRequiredMixin, DeleteView):
    template_name = 'lecture_confirm_delete.html'
    model = LECTURES
    context_object_name = 'lecture'
    def get_object(self, queryset=None):
        course_name = self.kwargs.get('courseName')
        lecture_name = self.kwargs.get('lectureName')
        instr = get_object_or_404(INSTRUCTOR, USER_NAME=self.request.user.USER_NAME)
        # Fetch the specific lecture by course name, lecture name, and instructor
        return get_object_or_404(LECTURES, NAME=lecture_name, course__COURSE_NAME=course_name, course__instructor=instr)

    def get_success_url(self):
        # Redirect to instructor's dashboard after successful deletion
        return reverse_lazy('instructor:Dashboard')

                              
@user_type_required('instructor')
def Dashboard(request):
    instruct = INSTRUCTOR.objects.get(USER_NAME = request.user)
    print(instruct)
   
    courses = COURSES.objects.filter(instructor = instruct)
    COURSES_STUDENTS= {}
    for coursY in courses:
        students = COURSE_LIST.objects.filter(course=coursY).count()
        COURSES_STUDENTS[coursY]=students
    cash_key = f"user_status_{request.user.id}"
    status = cache.get(cash_key)
   
    return render(request,'DTashboard.html',{'courses':COURSES_STUDENTS,'status':status}) 

@user_type_required('instructor')
def CreateCourse(request):
    if request.method == 'POST':
        form = CreateForm(request.POST, request.FILES)
        print(request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            instruc = INSTRUCTOR.objects.get(USER_NAME = request.user)
            try:
                cour = COURSES.objects.create(COURSE_NAME=cd["COURSE_NAME"], COVER_PHOTO = cd["COVER_PHOTO"], IsDraft=cd["IsDraft"], instructor=instruc)
                return redirect ('instructor:Dashboard')
            except:
                print("why we here")
                return render (request , "CreateCourse.html", {'form':form})
        else:
            print(form.errors)
            return render (request , "CreateCourse.html", {'form':form})
    else:
        form = CreateForm()
        return render (request , "CreateCourse.html", {'form':form})


def AddLecture(request, courseName):
    if request.method == 'POST':
        form = AddLectureForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            Course = COURSES.objects.get(COURSE_NAME=courseName)
            instru = INSTRUCTOR.objects.get(USER_NAME = request.user)
            lecture = LECTURES.objects.create(**cd, course=Course)
            message ="lecture added successfully"
            return redirect('instructor:Dashboard')
        else:
            return render(request, 'AddLecture.html', {'form':form, 'course':courseName})

    else:
        form = AddLectureForm()
        return render(request, 'AddLecture.html', {'form':form, 'course':courseName})

def HandlLectures(request,courseName):
    Course = COURSES.objects.get(COURSE_NAME = courseName)
    lectures = LECTURES.objects.filter(course = Course)
    print(lectures.count())
    return render(request, 'HandlLectures.html',{'lectures':lectures, 'course':courseName})
    
def Publish(request, courseName):
    instr = INSTRUCTOR.objects.get(USER_NAME = request.user)
    course = COURSES.objects.get(COURSE_NAME=courseName, instructor= instr)
    course.IsDraft = False
    course.save()
    message= "your course published successfully"
    return redirect('instructor:Dashboard')
def Block(request):
    if request.method == 'POST':
        cd = request.POST.get('blocked')
        print(f' here is the blocked student{cd}')
        try:
            BAD_STUDENT = STUDENT.objects.get(USER_NAME = cd)
            instruc = INSTRUCTOR.objects.get(USER_NAME = request.user)
            blocked = BLOCK_LIST.objects.create(students = BAD_STUDENT , instructors = instruc )
            blocked.save()
        except:
            message = "no user matched your input "
           
        return redirect('instructor:Dashboard')

       
def UnBlock(request):
    if request.method == 'POST':
        cd = request.POST.get('unblocked')
        print(f'cd is {cd}')
        try:
            BAD_STUDENT = STUDENT.objects.get(USER_NAME = cd)
            print(f'bad student is {BAD_STUDENT}')
            instruc = INSTRUCTOR.objects.get(USER_NAME = request.user.USER_NAME)
            unblocked = BLOCK_LIST.objects.get(students = BAD_STUDENT , instructors = instruc )
            unblocked.delete()
            message = "learner unblocked successfully"
        except:
            message = "no user matched your input"
           
        return redirect('instructor:Dashboard')    
def SendToFollowers(request, courseName):
    if request.method == 'POST':
        message = request.POST.get('message')
        course = COURSES.objects.get(COURSE_NAME = courseName)
        students = COURSE_LIST.objects.filter(course = course)
        print(message)
        for student in students:

            send_email(student.student.EMAIL, message)
        
        return redirect("instructor:Dashboard")

ELEARN_BACKEND/INSTRUCTOR/templates/AddLecture.html
{%extends 'base.html'%}
{% load static%}


{%block title%} add lecture {%endblock%}
{%block main%}
    <form action="{%url 'instructor:AddLecture' course%}" method="post">
        {%csrf_token%}
        {{form}}
        <input type="submit" value="submit" />
    </form>
    <h2> can edit lectures after publishing them</h2>
{%endblock%}

ELEARN_BACKEND/INSTRUCTOR/templates/CreateCourse.html
{%extends 'base.html'%}
{% load static%}


{%block title%} create course  {%endblock%}
{%block main%}
    <form action="{%url 'instructor:CreateCourse'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {{form}}
        <input type="submit" value="submit" />
    </form>
{%endblock%}

ELEARN_BACKEND/INSTRUCTOR/templates/DTashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Dashboard {% endblock %}

{% block main %}
<div class="container mx-auto px-4 py-8">
    <!-- New Course Section -->
    <div class="mb-8">
        <h1 class="text-2xl font-bold text-gray-800">
            Ready to create a new course? <a href="{% url 'instructor:CreateCourse' %}" class="text-blue-600 hover:underline">Click here</a>
        </h1>
    </div>
    <div>
        <div>
            <h1> status area</h1>
            <form method="post" action="{% url 'instructor:update_status' %}">
                {% csrf_token %}
                <textarea name="status" placeholder="Enter your status"></textarea>
                <button type="submit">Update Status</button>
            </form>
            
            {% if status %}
                <p>Your current status: {{ status }}</p>
            {% else %}
                <p>You have not set a status yet.</p>
            {% endif %}
        </div>
    </div>
    <!-- Published Courses Section -->
    <div class="mb-8">
        <h1 class="text-xl font-semibold text-gray-800 mb-4">Published Courses</h1>
        <table class="min-w-full bg-white border border-gray-300 rounded-md shadow-md">
            <thead>
                <tr class="bg-gray-100 text-gray-800">
                    <th class="py-2 px-4 border-b">Course Name</th>
                    <th class="py-2 px-4 border-b">Enrolled Students</th>
                    <th class="py-2 px-4 border-b">Edit Course</th>
                    <th class="py-2 px-4 border-b">Delete Course</th>
                    <th class="py-2 px-4 border-b">Email Students</th>
                    <th class="py-2 px-4 border-b">Browse Profiles</th>
                </tr>
            </thead>
            <tbody>
                {% for course, student in courses.items %}
                {% if not course.IsDraft %}
                <tr class="text-gray-700">
                    <td class="py-2 px-4 border-b">{{ course.COURSE_NAME }}</td>
                    <td class="py-2 px-4 border-b">{{ student }}</td>
                    <td class="py-2 px-4 border-b"><a href="{% url 'instructor:course_detail' course.COURSE_NAME %}" class="text-blue-600 hover:underline">Edit</a></td>
                    <td class="py-2 px-4 border-b"><a href="{% url 'instructor:course_delete' course.COURSE_NAME %}" class="text-red-600 hover:underline">Delete</a></td>
                    <td class="py-2 px-4 border-b">
                        <form action="{%url 'instructor:SendToFollowers' course.COURSE_NAME%}" method="post">
                            {%csrf_token%}
                            <input type="text" name="message">
                            <button type="submit" value="submit" class="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700">send</button>
                        </form>
                         
                    
                    </td>
                    <td class="py-2 px-4 border-b"><a href=
                        "{%url 'instructor:Learners'%}" class="text-blue-600 hover:underline">Browse Profiles</a></td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Draft Courses Section -->
    <div class="mb-8">
        <h1 class="text-xl font-semibold text-gray-800 mb-4">Draft Courses</h1>
        <table class="min-w-full bg-white border border-gray-300 rounded-md shadow-md">
            <thead>
                <tr class="bg-gray-100 text-gray-800">
                    <th class="py-2 px-4 border-b">Course Name</th>
                    <th class="py-2 px-4 border-b">Add Lectures</th>
                    <th class="py-2 px-4 border-b">Delete Course</th>
                    <th class="py-2 px-4 border-b">Delete/Edit Lectures</th>
                    <th class="py-2 px-4 border-b">Publish Course</th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                {% if course.IsDraft %}
                <tr class="text-gray-700">
                    <td class="py-2 px-4 border-b">{{ course.COURSE_NAME }}</td>
                    <td class="py-2 px-4 border-b"><a href="{% url 'instructor:AddLecture' course.COURSE_NAME %}" class="text-blue-600 hover:underline">Add Lectures</a></td>
                    <td class="py-2 px-4 border-b"><a href="{% url 'instructor:course_delete' course.COURSE_NAME %}" class="text-red-600 hover:underline">Delete</a></td>
                    <td class="py-2 px-4 border-b"><a href="{% url 'instructor:HandlLectures' course.COURSE_NAME %}" class="text-yellow-600 hover:underline">Manage Lectures</a></td>
                    <td class="py-2 px-4 border-b"><a href="{% url 'instructor:Publish' course.COURSE_NAME %}" class="text-green-600 hover:underline">Publish</a></td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Students and Blocking Section -->
    <div class="mb-8">
        <h1 class="text-xl font-semibold text-gray-800 mb-4">Explore Your Students</h1>
        <p class="text-gray-600 mb-2">Find out what else your students are learning.</p>
        <a href="{%url 'instructor:Learners'%}" class="text-blue-600 hover:underline">Your Learners</a>
    </div>

    <!-- Block Abusers Section -->
    <div class="mb-8">
        <h1 class="text-xl font-semibold text-gray-800 mb-4">Block Abusers</h1>
        <p class="text-gray-600 mb-2">If you find harassment from any student, you can block them from all your courses by reporting their username using the form below.</p>
        <form action="{% url 'instructor:Block' %}" method="post" class="space-y-4">
            {% csrf_token %}
            <div>
                <label for="blocked" class="block text-gray-600">Username to block</label>
                <input type="text" name="blocked" id="blocked" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
            </div>
            <button type="submit" class="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700">Submit</button>
        </form>
    </div>

    <!-- Unblock Learners Section -->
    <div class="mb-8">
        <h1 class="text-xl font-semibold text-gray-800 mb-4">Unblock Learners</h1>
        <p class="text-gray-600 mb-2">Unblock learners so they can enroll again in your courses.</p>
        <form action="{% url 'instructor:UnBlock' %}" method="post" class="space-y-4">
            {% csrf_token %}
            <div>
                <label for="unblocked" class="block text-gray-600">Username to unblock</label>
                <input type="text" name="unblocked" id="unblocked" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
            </div>
            <button type="submit" class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">Submit</button>
        </form>
    </div>

    <!-- Footer Message Section -->
    <footer class="text-center mt-8">
        <p class="text-gray-600">{{ message }}</p>
    </footer>
</div>
{% endblock %}

ELEARN_BACKEND/INSTRUCTOR/templates/HandlLectures.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Process Lectures {% endblock %}
{% block main %}
<div class="container mx-auto mt-8">
    <h1 class="text-2xl font-bold mb-6">Lectures</h1>
    <table class="min-w-full bg-white border border-gray-300">
        <thead>
            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                <th class="py-3 px-6 text-left">Lecture Name</th>
                <th class="py-3 px-6 text-center">Delete</th>
            </tr>
        </thead>
        <tbody class="text-gray-600 text-sm font-light">
            {% for lecture in lectures %}
            <tr class="border-b border-gray-200 hover:bg-gray-100">
                <td class="py-3 px-6 text-left">{{ lecture }}</td>

                <td class="py-3 px-6 text-center">
                    <a href="{%url 'instructor:DeleteLecture' course lecture.NAME%}" class="text-red-600 hover:text-red-800">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

ELEARN_BACKEND/INSTRUCTOR/templates/course_confirm_delete.html
<form method="post">{% csrf_token %}
     
 
 
 
    <p>Are you sure you want to delete that course this process is <strong> irreversable </strong></p>
     
     
     
     
        <input type="submit" value="Confirm">
    </form>
    <a href="{% url 'instructor:Dashboard'%}"> do not delete return me </a>

ELEARN_BACKEND/INSTRUCTOR/templates/course_detail.html
{%extends 'base.html'%}
{% load static%}


{%block title%} course details {%endblock%}
{% block main %}
    <h1>{{ course.COURSE_NAME }}</h1>
    <div class="container mx-auto mt-8">
        <h1 class="text-2xl font-bold mb-6">Lectures</h1>
        <table class="min-w-full bg-white border border-gray-300">
            <thead>
                <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                    <th class="py-3 px-6 text-left">Lecture Name</th>
                    <th class="py-3 px-6 text-center">Delete</th>
                </tr>
            </thead>
            <tbody class="text-gray-600 text-sm font-light">
                {% for lecture in courseLectures %}
                <tr class="border-b border-gray-200 hover:bg-gray-100">
                    <td class="py-3 px-6 text-left">{{ lecture.NAME }}</td>

                    <td class="py-3 px-6 text-center">
                        <a href="{%url 'instructor:DeleteLecture' course.COURSE_NAME lecture.NAME%}" class="text-red-600 hover:text-red-800">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <a href="{% url 'instructor:AddLecture' course.COURSE_NAME %}">Add Lectures</a>
{% endblock %}